/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

import java.net.URI;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class Calc extends javax.swing.JFrame {
    
    private String showVal = "0";
    private StringBuilder sb;
    private double a,b,c;
    private Double doubObj;
    private int opt;
    private int pntSet,signSet;
    private int count;
    private String[][] rowData;
    private DefaultTableModel calcModel;
    private Connection connection;
    private String colName[] ={
        "operand_a","operand_b","operator","result","username"
    };
    
    public Calc() {
        signSet = 0;
        pntSet = 0;
        a = 0;
        b = 0;
        c = 0;
        opt = 0;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        buttonMult = new javax.swing.JButton();
        buttonMinus = new javax.swing.JButton();
        buttonPlus = new javax.swing.JButton();
        buttonDevide = new javax.swing.JButton();
        buttonSign = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        buttonPoint = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        buttonEq = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        buttonDel = new javax.swing.JButton();
        buttonCmInch = new javax.swing.JButton();
        buttonKmMile = new javax.swing.JButton();
        buttonGgle = new javax.swing.JButton();
        buttonSaveOp = new javax.swing.JButton();
        buttonShowHist = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setText(showVal);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonMult.setText("x");
        buttonMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultActionPerformed(evt);
            }
        });

        buttonMinus.setText("-");
        buttonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMinusActionPerformed(evt);
            }
        });

        buttonPlus.setText("+");
        buttonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlusActionPerformed(evt);
            }
        });

        buttonDevide.setText("/");
        buttonDevide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDevideActionPerformed(evt);
            }
        });

        buttonSign.setText("-/+");
        buttonSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignActionPerformed(evt);
            }
        });

        button7.setText("7");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        button4.setText("4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button1.setText("1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        buttonPoint.setText(".");
        buttonPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPointActionPerformed(evt);
            }
        });

        button8.setText("8");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        button5.setText("5");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button2.setText("2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button9.setText("9");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        button6.setText("6");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button3.setText("3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        buttonEq.setText("=");
        buttonEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEqActionPerformed(evt);
            }
        });

        button0.setText("0");
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });

        buttonClear.setText("C");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        buttonDel.setText("Del");
        buttonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDelActionPerformed(evt);
            }
        });

        buttonCmInch.setText("cm to inch");
        buttonCmInch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCmInchActionPerformed(evt);
            }
        });

        buttonKmMile.setText("km to mile");
        buttonKmMile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKmMileActionPerformed(evt);
            }
        });

        buttonGgle.setText("Google something!");
        buttonGgle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGgleActionPerformed(evt);
            }
        });

        buttonSaveOp.setText("save operation");
        buttonSaveOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveOpActionPerformed(evt);
            }
        });

        buttonShowHist.setText("show history");
        buttonShowHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowHistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonSign)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonDevide)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonPlus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMinus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMult))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonSaveOp)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(buttonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(button0)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(buttonEq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(button1)
                                                .addComponent(button4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(button2)
                                                .addComponent(button5)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(button7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(button8)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(button3)
                                        .addComponent(button6)
                                        .addComponent(button9)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonShowHist)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(buttonClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonDel))
                            .addComponent(buttonCmInch)
                            .addComponent(buttonKmMile)
                            .addComponent(buttonGgle))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMult)
                    .addComponent(buttonMinus)
                    .addComponent(buttonPlus)
                    .addComponent(buttonDevide)
                    .addComponent(buttonSign))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(button5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button9)
                            .addComponent(buttonDel)
                            .addComponent(buttonClear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button6)
                            .addComponent(buttonCmInch))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(button3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(buttonKmMile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonGgle))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button7)
                            .addComponent(button8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonPoint)
                            .addComponent(button0)
                            .addComponent(buttonEq))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSaveOp)
                    .addComponent(buttonShowHist))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setName(""); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "operand_a", "operand_b", "operator", "result", "username"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        if(showVal.length() == 15);
        else if(showVal.equalsIgnoreCase("0")) {
            showVal="1";
            jTextField1.setText(showVal);
        }
        else
        {
            sb = new StringBuilder(showVal);
            sb.append("1");
            showVal = sb.toString();
            jTextField1.setText(showVal);
        }
        
    }//GEN-LAST:event_button1ActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        // TODO add your handling code here:
        showVal = "0";
        pntSet = 0;
        signSet = 0;
        jTextField1.setText(showVal);
    }//GEN-LAST:event_buttonClearActionPerformed

    private void buttonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDelActionPerformed
        // TODO add your handling code here:
        sb = new StringBuilder(showVal);
        
        if(sb.length() == 1){
            showVal = "0";
            jTextField1.setText(showVal);
        }
        else{
        sb.deleteCharAt(sb.length()-1);
        showVal = sb.toString();
        jTextField1.setText(showVal);
        }
    }//GEN-LAST:event_buttonDelActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        // TODO add your handling code here:
        if(showVal.length() == 15);
        else
        {
            sb = new StringBuilder(showVal);
            sb.append("0");
            showVal = sb.toString();
            jTextField1.setText(showVal);
        }
    }//GEN-LAST:event_button0ActionPerformed

    private void buttonCmInchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCmInchActionPerformed
        // TODO add your handling code here:
        a = Double.parseDouble(showVal);
        c = a*(0.393701);
        doubObj = new Double(c);
        showVal = doubObj.toString();
        jTextField1.setText(showVal);
        pntSet = 0;
        signSet = 0;
    }//GEN-LAST:event_buttonCmInchActionPerformed

    private void buttonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlusActionPerformed
        // TODO add your handling code here:
        a = Double.parseDouble(showVal);
        showVal = "0";
        jTextField1.setText(showVal);
        opt = 3;
        pntSet = 0;
        signSet = 0;
    }//GEN-LAST:event_buttonPlusActionPerformed

    private void buttonEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEqActionPerformed
        // TODO add your handling code here:
        switch (opt) {
            case 2:
                b = Double.parseDouble(showVal);
                c = a / b;
                doubObj = new Double(c);
                showVal = doubObj.toString();
                jTextField1.setText(showVal);
                showVal = "";
                break;
            case 3:
                b = Double.parseDouble(showVal);
                c = (a+b);
                doubObj = new Double(c);
                showVal = doubObj.toString();
                jTextField1.setText(showVal);
                showVal = "";
                break;
            case 4:
                b = Double.parseDouble(showVal);
                c = a - b;
                doubObj = new Double(c);
                showVal = doubObj.toString();
                jTextField1.setText(showVal);
                showVal = "";
                break;
            case 5:
                b = Double.parseDouble(showVal);
                c = a * b;
                doubObj = new Double(c);
                showVal = doubObj.toString();
                jTextField1.setText(showVal);
                showVal = "";
                break;
            default:
                break;
        }
    }//GEN-LAST:event_buttonEqActionPerformed

    private void buttonGgleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGgleActionPerformed
        try {
            // TODO add your handling code here:
            java.awt.Desktop.getDesktop().browse(new URI("https://www.google.com/"));
        } catch (Exception ex) {
            System.out.println("error"+ ex.toString());
        }
    }//GEN-LAST:event_buttonGgleActionPerformed

    private void buttonSaveOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveOpActionPerformed
        // TODO add your handling code here:
        DBinOut dbsave = new DBinOut();
        dbsave.setOprdA(a);
        dbsave.setOprdB(b);
        dbsave.setRslt(c);
        dbsave.setOpt(opt);
        dbsave.setUsrnm(Calculator.usrnm);
        dbsave.saveHist();
        JOptionPane.showMessageDialog(null, "your history is saved", "Saved", JOptionPane.PLAIN_MESSAGE);
        
    }//GEN-LAST:event_buttonSaveOpActionPerformed

    private void buttonShowHistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowHistActionPerformed
        // TODO add your handling code here:
        //DBinOut dbshow = new DBinOut();
        getRsltCalcTble();
        calcModel = new DefaultTableModel(rowData, colName);
        jTable1.setModel(calcModel);
        //dbshow.getHist();
    }//GEN-LAST:event_buttonShowHistActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        if(showVal.length() == 15);
        else if(showVal.equalsIgnoreCase("0")) {
            showVal="2";
            jTextField1.setText(showVal);
        }
        else
        {
            sb = new StringBuilder(showVal);
            sb.append("2");
            showVal = sb.toString();
            jTextField1.setText(showVal);
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        if(showVal.length() == 15);
        else if(showVal.equalsIgnoreCase("0")) {
            showVal="3";
            jTextField1.setText(showVal);
        }
        else
        {
            sb = new StringBuilder(showVal);
            sb.append("3");
            showVal = sb.toString();
            jTextField1.setText(showVal);
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        if(showVal.length() == 15);
        else if(showVal.equalsIgnoreCase("0")) {
            showVal="4";
            jTextField1.setText(showVal);
        }
        else
        {
            sb = new StringBuilder(showVal);
            sb.append("4");
            showVal = sb.toString();
            jTextField1.setText(showVal);
        }
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        if(showVal.length() == 15);
        else if(showVal.equalsIgnoreCase("0")) {
            showVal="5";
            jTextField1.setText(showVal);
        }
        else
        {
            sb = new StringBuilder(showVal);
            sb.append("5");
            showVal = sb.toString();
            jTextField1.setText(showVal);
        }
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        if(showVal.length() == 15);
        else if(showVal.equalsIgnoreCase("0")) {
            showVal="6";
            jTextField1.setText(showVal);
        }
        else
        {
            sb = new StringBuilder(showVal);
            sb.append("6");
            showVal = sb.toString();
            jTextField1.setText(showVal);
        }
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
        if(showVal.length() == 15);
        else if(showVal.equalsIgnoreCase("0")) {
            showVal="7";
            jTextField1.setText(showVal);
        }
        else
        {
            sb = new StringBuilder(showVal);
            sb.append("7");
            showVal = sb.toString();
            jTextField1.setText(showVal);
        }
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
        if(showVal.length() == 15);
        else if(showVal.equalsIgnoreCase("0")) {
            showVal="8";
            jTextField1.setText(showVal);
        }
        else
        {
            sb = new StringBuilder(showVal);
            sb.append("8");
            showVal = sb.toString();
            jTextField1.setText(showVal);
        }
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
        if(showVal.length() == 15);
        else if(showVal.equalsIgnoreCase("0")) {
            showVal="9";
            jTextField1.setText(showVal);
        }
        else
        {
            sb = new StringBuilder(showVal);
            sb.append("9");
            showVal = sb.toString();
            jTextField1.setText(showVal);
        }
    }//GEN-LAST:event_button9ActionPerformed

    private void buttonPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPointActionPerformed
        // TODO add your handling code here:
        if(showVal.length() == 15);
        else if(pntSet == 1);
        else
        {
            sb = new StringBuilder(showVal);
            sb.append(".");
            showVal = sb.toString();
            jTextField1.setText(showVal);
            pntSet = 1;
        }
    }//GEN-LAST:event_buttonPointActionPerformed

    private void buttonKmMileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKmMileActionPerformed
        // TODO add your handling code here:
        a = Double.parseDouble(showVal);
        c = a*(0.621371);
        doubObj = new Double(c);
        showVal = doubObj.toString();
        jTextField1.setText(showVal);
        pntSet = 0;
        signSet = 0;
    }//GEN-LAST:event_buttonKmMileActionPerformed

    private void buttonDevideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDevideActionPerformed
        // TODO add your handling code here:
        a = Double.parseDouble(showVal);
        showVal = "0";
        jTextField1.setText(showVal);
        opt = 2;
        pntSet = 0;
        signSet = 0;
    }//GEN-LAST:event_buttonDevideActionPerformed

    private void buttonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMinusActionPerformed
        // TODO add your handling code here:
        a = Double.parseDouble(showVal);
        showVal = "0";
        jTextField1.setText(showVal);
        opt = 4;
        pntSet = 0;
        signSet = 0;
    }//GEN-LAST:event_buttonMinusActionPerformed

    private void buttonMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultActionPerformed
        // TODO add your handling code here:
        a = Double.parseDouble(showVal);
        showVal = "0";
        jTextField1.setText(showVal);
        opt = 5;
        pntSet = 0;
        signSet = 0;
    }//GEN-LAST:event_buttonMultActionPerformed

    private void buttonSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignActionPerformed
        // TODO add your handling code here:
        if(showVal.length() == 15);
        else if(signSet == 1){
            if(showVal.equalsIgnoreCase("0")) showVal = "";
            sb = new StringBuilder(showVal);
            sb.delete(0,1);
            showVal = sb.toString();
            jTextField1.setText(showVal);
            signSet = 0; 
        }
        else if (signSet == 0)
        {
            if(showVal.equalsIgnoreCase("0")) showVal = "";
            sb = new StringBuilder(showVal);
            sb.insert(0,'-');
            showVal = sb.toString();
            jTextField1.setText(showVal);
            signSet = 1;
        }
        
    }//GEN-LAST:event_buttonSignActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Calc().setVisible(true);
            }
        });
        
    }
    public ResultSet getRsltCalcTble() {
        ResultSet rs=null;
        try{
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/zakidb", "root", "hello");
            System.out.println("connected to database");
            Statement stmt = connection.createStatement();
            rs=stmt.executeQuery("Select * from calculator_record");
            while (rs.next() ) {
                    System.out.print(rs.getString(3));
            }
            rs=stmt.executeQuery("Select * from calculator_record");
            while (rs.next()) {
                ++count;
                System.out.println("counting!");
            }
            rs=stmt.executeQuery("Select * from calculator_record");
            rowData = new String[count][5];
            System.out.println("after counting ");
            int i = 0;
            while (rs.next())
            {
                System.out.println("some data");
                rowData[i][0] = rs.getString(1);
                rowData[i][1] = rs.getString("operand_b");
                rowData[i][2] = rs.getString("operator");
                rowData[i][3] = rs.getString(4);
                rowData[i][4] = rs.getString(5);
                ++i;
                System.out.println("rani hna");
            }
        
        }
        catch(SQLException e){ System.out.println("me you! "+e.toString()+" yes");}
        
        return rs;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonCmInch;
    private javax.swing.JButton buttonDel;
    private javax.swing.JButton buttonDevide;
    private javax.swing.JButton buttonEq;
    private javax.swing.JButton buttonGgle;
    private javax.swing.JButton buttonKmMile;
    private javax.swing.JButton buttonMinus;
    private javax.swing.JButton buttonMult;
    private javax.swing.JButton buttonPlus;
    private javax.swing.JButton buttonPoint;
    private javax.swing.JButton buttonSaveOp;
    private javax.swing.JButton buttonShowHist;
    private javax.swing.JButton buttonSign;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
